(async function initializeMailSystem(){
const { initializeApp } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-app.js");
const { getFirestore, collection, addDoc, getDocs, updateDoc, deleteDoc, doc } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-firestore.js");
const { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-auth.js");

const firebaseConfig={apiKey:"AIzaSyCzvPwTbxc_Lg7peKRgP0zUrlmI6kkE0b4",authDomain:"seal-management-68465.firebaseapp.com",projectId:"seal-management-68465",storageBucket:"seal-management-68465.firebasestorage.app",messagingSenderId:"933578260928",appId:"1:933578260928:web:4c5f41252fd786e1bf0825",measurementId:"G-7RKPNF7BK9"};
const app=initializeApp(firebaseConfig); const db=getFirestore(app); const auth=getAuth(app); const provider=new GoogleAuthProvider();
const MAIL_TYPES=["掛號","限掛","平信","黑貓宅急便","其他"];
let currentRole="",currentUser="系統使用者",currentUserEmail="";
let mailRecords=[],departmentList=[],userList=[],auditLogs=[],loginLogs=[];
let currentPage=1,pageSize=10,auditCurrentPage=1,auditPageSize=25,loginCurrentPage=1,loginPageSize=10;
let selectedSheetRecords=[];

function $(id){return document.getElementById(id)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function todayStr(){return new Date().toISOString().slice(0,10)}
function ymStr(d=new Date()){return d.toISOString().slice(0,7)}
function formatDate(v){if(!v)return "-"; if(v.seconds)return new Date(v.seconds*1000).toLocaleString("zh-TW"); if(/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return String(v).replaceAll("-","/"); return new Date(v).toLocaleString("zh-TW")}
function getTime(v){if(!v)return 0;if(v.seconds)return v.seconds*1000;return new Date(v).getTime()||0}
function canAdmin(){return currentRole==="admin"}
function blockUserAdminAction(){ if(canAdmin()) return false; alert("此功能僅限 Admin 使用"); return true; }
function mailLabel(r){return r.trackingNo||r.receiver||r.subject||r.id||"郵件"}

async function writeAuditLog({action,category,targetId="",targetLabel="",before=null,after=null}){try{await addDoc(collection(db,"mailAuditLogs"),{actorName:currentUser,actorEmail:currentUserEmail,actorRole:currentRole,action,category,targetId,targetLabel,before:compact(before),after:compact(after),createdAt:new Date()})}catch(e){console.error("audit fail",e)}}
function compact(data){if(!data)return null;const out={};Object.entries(data).forEach(([k,v])=>{if(k==="id")return;if(v===null||["string","number","boolean"].includes(typeof v))out[k]=v});return out}

function applyRoleAccess(){document.querySelectorAll(".admin-only").forEach(el=>el.style.display=canAdmin()?"":"none");$("systemMenuTitle").style.display=canAdmin()?"":"none"}
function toggleSidebar(){ $("sidebar").classList.toggle("collapsed") }
window.toggleSidebar=toggleSidebar;
function showPage(pageId,el){const adminPages=["deptPage","permissionPage","auditLogPage","loginLogPage"];if(!canAdmin()&&adminPages.includes(pageId)){pageId="dashboardPage";el=document.querySelector('[onclick*=dashboardPage]')}document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(pageId)?.classList.remove("hidden");document.querySelectorAll(".menu-item").forEach(i=>i.classList.remove("active"));if(el)el.classList.add("active");localStorage.setItem("mailLastPage",pageId); if(window.lucide) lucide.createIcons();}
window.showPage=showPage;
function restoreLastPage(){const last=localStorage.getItem("mailLastPage")||"dashboardPage";const menu=document.querySelector(`[onclick*="${last}"]`)||document.querySelector('[onclick*=dashboardPage]');showPage(last,menu)}

function renderDropdowns(){const typeOptions=MAIL_TYPES.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("");$("mailType").innerHTML=typeOptions;$("typeFilter").innerHTML=`<option value="">全部類型</option>`+typeOptions;const deptOptions=departmentList.map(d=>`<option value="${esc(d.name)}">${esc(d.name)}</option>`).join("");$("department").innerHTML=`<option value="">請選擇</option>`+deptOptions;$("deptFilter").innerHTML=`<option value="">全部部門</option>`+deptOptions;}

async function loadDepartments(){const snap=await getDocs(collection(db,"departments"));departmentList=[];snap.forEach(s=>departmentList.push({id:s.id,...s.data(),sortOrder:Number(s.data().sortOrder||999)}));departmentList.sort((a,b)=>a.sortOrder-b.sortOrder);renderDropdowns();renderDepartmentMaintenance();}
async function loadUsers(){const snap=await getDocs(collection(db,"users"));userList=[];snap.forEach(s=>userList.push({id:s.id,...s.data()}));renderUserList()}
async function loadMailRecords(){const snap=await getDocs(collection(db,"mailRecords"));mailRecords=[];snap.forEach(s=>mailRecords.push({id:s.id,...s.data()}));mailRecords.sort((a,b)=>(getTime(b.createdTime)||Date.parse(b.receiveDate||0))-(getTime(a.createdTime)||Date.parse(a.receiveDate||0)));renderDashboard();renderMailTable();renderSheetPage();}

function resetMailForm(){["mailId","trackingNo","sender","receiver","subject","remark"].forEach(id=>$(id).value="");$("receiveDate").value=todayStr();$("mailType").value="掛號";$("department").value="";}
window.resetMailForm=resetMailForm;
async function saveMailRecord(){const id=$("mailId").value;const data={receiveDate:$("receiveDate").value,mailType:$("mailType").value,trackingNo:$("trackingNo").value.trim(),sender:$("sender").value.trim(),department:$("department").value,receiver:$("receiver").value.trim(),subject:$("subject").value.trim(),remark:$("remark").value.trim()};if(!data.receiveDate||!data.mailType||!data.sender||!data.department||!data.receiver){alert("請填寫收件日期、郵件類型、寄件人、收件部門、收件人");return}if(id){const before=mailRecords.find(r=>r.id===id);await updateDoc(doc(db,"mailRecords",id),data);await writeAuditLog({action:"update",category:"mailRecord",targetId:id,targetLabel:mailLabel(data),before,after:{...before,...data}});alert("修改成功")}else{const ref=await addDoc(collection(db,"mailRecords"),{...data,printed:false,createdBy:currentUser,createdByEmail:currentUserEmail,createdTime:new Date()});await writeAuditLog({action:"create",category:"mailRecord",targetId:ref.id,targetLabel:mailLabel(data),after:{...data,printed:false}});alert("登錄成功")}resetMailForm();await loadMailRecords();}
window.saveMailRecord=saveMailRecord;
function editMail(id){const r=mailRecords.find(x=>x.id===id);if(!r)return;showPage("registerPage",document.querySelector('[onclick*=registerPage]'));$("mailId").value=id;$("receiveDate").value=r.receiveDate||todayStr();$("mailType").value=r.mailType||"掛號";$("trackingNo").value=r.trackingNo||"";$("sender").value=r.sender||"";$("department").value=r.department||"";$("receiver").value=r.receiver||"";$("subject").value=r.subject||"";$("remark").value=r.remark||"";}
window.editMail=editMail;
async function deleteMail(id){const r=mailRecords.find(x=>x.id===id);if(!confirm("確定刪除此筆郵件資料？"))return;await deleteDoc(doc(db,"mailRecords",id));await writeAuditLog({action:"delete",category:"mailRecord",targetId:id,targetLabel:mailLabel(r),before:r});await loadMailRecords();}
window.deleteMail=deleteMail;
async function togglePrinted(id,printed){const r=mailRecords.find(x=>x.id===id);await updateDoc(doc(db,"mailRecords",id),{printed:!printed,printedAt:!printed?new Date():null,printedBy:!printed?currentUser:""});await writeAuditLog({action:"update",category:"mailRecord",targetId:id,targetLabel:mailLabel(r),before:r,after:{...r,printed:!printed}});await loadMailRecords();}
window.togglePrinted=togglePrinted;

function renderDashboard(){const today=todayStr(),month=ymStr();const todayRecords=mailRecords.filter(r=>r.receiveDate===today);$("kpiToday").textContent=todayRecords.length;$("kpiPendingPrint").textContent=mailRecords.filter(r=>!r.printed).length;$("kpiMonth").textContent=mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)).length;$("kpiRegistered").textContent=mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)&&["掛號","限掛"].includes(r.mailType)).length;renderSummary("todayDeptSummary",groupCount(todayRecords,"department"));renderSummary("typeSummary",groupCount(mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)),"mailType"));}
function groupCount(list,key){const m={};list.forEach(r=>{const k=r[key]||"未分類";m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function renderSummary(id,rows){$(id).innerHTML=rows.length?rows.map(([k,v])=>`<div class="summary-item"><strong>${esc(k)}</strong><span>${v} 件</span></div>`).join(""):`<div class="summary-item"><strong>目前無資料</strong><span>0 件</span></div>`}

function getFilteredRecords(){const kw=($("searchInput")?.value||"").toLowerCase();const type=$("typeFilter")?.value||"";const dept=$("deptFilter")?.value||"";const printed=$("printedFilter")?.value||"";const start=$("dateStart")?.value||"";const end=$("dateEnd")?.value||"";return mailRecords.filter(r=>{const text=[r.trackingNo,r.sender,r.department,r.receiver,r.subject,r.remark,r.mailType].join(" ").toLowerCase();return (!kw||text.includes(kw))&&(!type||r.mailType===type)&&(!dept||r.department===dept)&&(!printed||(printed==="printed"?r.printed:!r.printed))&&(!start||r.receiveDate>=start)&&(!end||r.receiveDate<=end)})}
function renderMailTable(){const table=$("mailTable");if(!table)return;const filtered=getFilteredRecords();$("recordCount").textContent=filtered.length;const total=Math.ceil(filtered.length/pageSize)||1;if(currentPage>total)currentPage=1;const pageRows=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);table.innerHTML=pageRows.length?pageRows.map(r=>`<tr><td>${esc(formatDate(r.receiveDate))}</td><td>${esc(r.mailType)}</td><td>${esc(r.trackingNo||"-")}</td><td>${esc(r.sender)}</td><td>${esc(r.department)}</td><td>${esc(r.receiver)}</td><td style="text-align:left;min-width:180px;">${esc(r.subject||"-")}</td><td>${r.printed?'<span class="badge badge-green">已列印</span>':'<span class="badge badge-yellow">未列印</span>'}</td><td><button class="btn btn-gray" onclick="editMail('${r.id}')">編輯</button> <button class="btn btn-gray" onclick="togglePrinted('${r.id}',${!!r.printed})">${r.printed?'改未列印':'標記列印'}</button> <button class="btn btn-red" onclick="deleteMail('${r.id}')">刪除</button></td></tr>`).join(""):`<tr><td colspan="9">目前沒有符合條件的郵件資料</td></tr>`;renderPagination(total)}
function renderPagination(total){const area=$("paginationArea");if(!area)return;area.innerHTML="";if(total<=1)return;for(let i=1;i<=total;i++){const b=document.createElement("button");b.className="btn";b.textContent=i;b.style.background=i===currentPage?"#2563eb":"#e2e8f0";b.style.color=i===currentPage?"white":"#0f172a";b.onclick=()=>{currentPage=i;renderMailTable()};area.appendChild(b)}}
function changePageSize(){pageSize=parseInt($("pageSizeSelect").value);currentPage=1;renderMailTable()} window.changePageSize=changePageSize;
function resetHistoryFilter(){["searchInput","typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].forEach(id=>$(id).value="");currentPage=1;renderMailTable()} window.resetHistoryFilter=resetHistoryFilter;
function toggleAdvancedFilter(){const p=$("advancedFilter"),t=$("filterToggleText");p.classList.toggle("show");t.textContent=p.classList.contains("show")?"收合篩選":"進階篩選"} window.toggleAdvancedFilter=toggleAdvancedFilter;
function exportExcel(){const data=getFilteredRecords().map(r=>({收件日期:formatDate(r.receiveDate),郵件類型:r.mailType,掛號單號:r.trackingNo||"",寄件人:r.sender,收件部門:r.department,收件人:r.receiver,主旨:r.subject||"",備註:r.remark||"",列印狀態:r.printed?"已列印":"未列印",登錄人:r.createdBy||""}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"郵件簽收紀錄");XLSX.writeFile(wb,"郵件簽收紀錄.xlsx")} window.exportExcel=exportExcel;

function renderSheetPage(){if(!$("sheetDeptList"))return;if(!$("sheetDate").value)$("sheetDate").value=todayStr();const date=$("sheetDate").value;const only=$("sheetOnlyUnprinted").checked;const rows=mailRecords.filter(r=>(!date||r.receiveDate===date)&&(!only||!r.printed));const grouped=groupCount(rows,"department");$("sheetDeptList").innerHTML=grouped.length?grouped.map(([dept,count])=>`<label class="dept-check-card"><div><strong>${esc(dept)}</strong><br><span>${count} 件郵件</span></div><input type="checkbox" class="sheet-dept-check" value="${esc(dept)}"></label>`).join(""):`<div class="summary-item"><strong>沒有可產生簽收單的郵件</strong><span>0 件</span></div>`;}
window.renderSheetPage=renderSheetPage;
function selectAllSheetDepartments(flag){document.querySelectorAll(".sheet-dept-check").forEach(c=>c.checked=flag)} window.selectAllSheetDepartments=selectAllSheetDepartments;
function generateSignSheet(){const depts=[...document.querySelectorAll(".sheet-dept-check:checked")].map(c=>c.value);if(!depts.length){alert("請先選擇至少一個部門");return}const date=$("sheetDate").value;const only=$("sheetOnlyUnprinted").checked;selectedSheetRecords=mailRecords.filter(r=>(!date||r.receiveDate===date)&&depts.includes(r.department)&&(!only||!r.printed));if(!selectedSheetRecords.length){alert("選取部門沒有可列印郵件");return}$("signSheetPreview").classList.remove("empty-preview");$("signSheetPreview").innerHTML=buildSignSheetHtml(selectedSheetRecords,date);}
window.generateSignSheet=generateSignSheet;
function buildSignSheetHtml(rows,date){const grouped={};rows.forEach(r=>{(grouped[r.department] ||= []).push(r)});let html=`<div class="sheet-doc"><div class="sheet-header"><h1>環興科技股份有限公司</h1><h2>郵件簽收單</h2></div><div class="sheet-meta"><div>收件日期：${esc(formatDate(date))}</div><div>列印時間：${esc(new Date().toLocaleString("zh-TW"))}</div><div>總件數：${rows.length} 件</div></div>`;Object.entries(grouped).forEach(([dept,list])=>{html+=`<div class="sheet-dept"><div class="sheet-dept-title">${esc(dept)}（${list.length}件）</div><table class="sheet-table"><thead><tr><th style="width:52px;">序號</th><th>類型</th><th>掛號 / 單號</th><th>寄件人</th><th>收件人</th><th>主旨 / 摘要</th><th style="width:110px;">簽收</th></tr></thead><tbody>`;list.forEach((r,i)=>{html+=`<tr><td style="text-align:center;">${i+1}</td><td>${esc(r.mailType)}</td><td>${esc(r.trackingNo||"-")}</td><td>${esc(r.sender)}</td><td>${esc(r.receiver)}</td><td>${esc(r.subject||"")}</td><td></td></tr>`});html+=`</tbody></table><div class="signature-row"><div>簽收人：________________</div><div>簽收日期：________________</div></div></div>`});return html+`</div>`}
async function markSelectedAsPrinted(){if(!selectedSheetRecords.length){alert("請先產生簽收單");return}if(!confirm(`確定將 ${selectedSheetRecords.length} 筆郵件標記為已列印？`))return;const batchNo=`MAIL-${Date.now()}`;for(const r of selectedSheetRecords){await updateDoc(doc(db,"mailRecords",r.id),{printed:true,printBatchNo:batchNo,printedAt:new Date(),printedBy:currentUser})}await writeAuditLog({action:"print",category:"signSheet",targetLabel:batchNo,after:{count:selectedSheetRecords.length,departments:[...new Set(selectedSheetRecords.map(r=>r.department))].join(",")}});alert("已標記為已列印");selectedSheetRecords=[];await loadMailRecords();}
window.markSelectedAsPrinted=markSelectedAsPrinted;

function renderDepartmentMaintenance(){const area=$("deptListArea");if(!area)return;area.innerHTML=departmentList.map(d=>`<div class="maintenance-item"><div><strong>${esc(d.name)}</strong><br><span>排序：${esc(d.sortOrder)}</span></div><div class="maintenance-actions"><button class="btn btn-gray" onclick="moveDept('${d.id}',-1)">上移</button><button class="btn btn-gray" onclick="moveDept('${d.id}',1)">下移</button><button class="btn btn-red" onclick="deleteDepartment('${d.id}')">刪除</button></div></div>`).join("")||"<p class='page-desc'>尚未建立部門。</p>"}
async function addDepartment(){if(blockUserAdminAction())return;const name=$("newDept").value.trim(),sortOrder=parseInt($("newDeptOrder").value||departmentList.length+1);if(!name){alert("請輸入部門名稱");return}const ref=await addDoc(collection(db,"departments"),{name,sortOrder});await writeAuditLog({action:"create",category:"department",targetId:ref.id,targetLabel:name,after:{name,sortOrder}});$("newDept").value="";$("newDeptOrder").value="";await loadDepartments()} window.addDepartment=addDepartment;
async function deleteDepartment(id){if(blockUserAdminAction())return;const d=departmentList.find(x=>x.id===id);if(!confirm(`確定刪除部門 ${d?.name||""}？`))return;await deleteDoc(doc(db,"departments",id));await writeAuditLog({action:"delete",category:"department",targetId:id,targetLabel:d?.name||id,before:d});await loadDepartments()} window.deleteDepartment=deleteDepartment;
async function moveDept(id,dir){if(blockUserAdminAction())return;const idx=departmentList.findIndex(d=>d.id===id);const ni=idx+dir;if(idx<0||ni<0||ni>=departmentList.length)return;[departmentList[idx],departmentList[ni]]=[departmentList[ni],departmentList[idx]];for(let i=0;i<departmentList.length;i++){await updateDoc(doc(db,"departments",departmentList[i].id),{sortOrder:i+1})}await loadDepartments()} window.moveDept=moveDept;

function renderUserList(){const area=$("userListArea");if(!area)return;area.innerHTML=userList.map(u=>`<div class="maintenance-item"><div><strong>${esc(u.email)}</strong><div style="margin-top:8px;display:flex;gap:12px;align-items:center;flex-wrap:wrap;"><span>角色：</span><select onchange="changeRole('${u.id}',this.value)"><option value="admin" ${u.role==="admin"?"selected":""}>Admin</option><option value="user" ${u.role==="user"?"selected":""}>User</option></select>${u.enabled?'<span class="badge badge-green">啟用</span>':'<span class="badge badge-red">停用</span>'}</div></div><div class="maintenance-actions"><button class="btn btn-gray" onclick="toggleUser('${u.id}',${!!u.enabled})">${u.enabled?'停用':'啟用'}</button><button class="btn btn-red" onclick="deleteUser('${u.id}')">刪除</button></div></div>`).join("")}
async function addWhitelistUser(){if(blockUserAdminAction())return;const email=$("newUserEmail").value.trim();if(!email){alert("請輸入 Email");return}const ref=await addDoc(collection(db,"users"),{email,role:"user",enabled:true});await writeAuditLog({action:"permission",category:"user",targetId:ref.id,targetLabel:email,after:{email,role:"user",enabled:true}});$("newUserEmail").value="";await loadUsers()} window.addWhitelistUser=addWhitelistUser;
async function changeRole(id,role){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);await updateDoc(doc(db,"users",id),{role});await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{...u,role}});await loadUsers()} window.changeRole=changeRole;
async function toggleUser(id,enabled){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);await updateDoc(doc(db,"users",id),{enabled:!enabled});await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{...u,enabled:!enabled}});await loadUsers()} window.toggleUser=toggleUser;
async function deleteUser(id){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);if(u?.role==="admin"){alert("管理員不可刪除");return}if(!confirm("確定刪除使用者？"))return;await deleteDoc(doc(db,"users",id));await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{deleted:true}});await loadUsers()} window.deleteUser=deleteUser;

async function loadAuditLogs(){if(!canAdmin())return;const snap=await getDocs(collection(db,"mailAuditLogs"));auditLogs=[];snap.forEach(s=>auditLogs.push({id:s.id,...s.data()}));auditLogs.sort((a,b)=>getTime(b.createdAt)-getTime(a.createdAt));renderAuditLogs()} window.loadAuditLogs=loadAuditLogs;
function renderAuditLogs(){const kw=($("auditSearch")?.value||"").toLowerCase(),act=$("auditActionFilter")?.value||"";const rows=auditLogs.filter(l=>(!act||l.action===act)&&(!kw||[l.actorName,l.actorEmail,l.targetLabel,JSON.stringify(l.after||{}),JSON.stringify(l.before||{})].join(" ").toLowerCase().includes(kw)));$("auditCount").textContent=`(${rows.length}筆)`;const total=Math.ceil(rows.length/auditPageSize)||1;if(auditCurrentPage>total)auditCurrentPage=1;const page=rows.slice((auditCurrentPage-1)*auditPageSize,auditCurrentPage*auditPageSize);$("auditLogTable").innerHTML=page.length?page.map(l=>`<tr><td>${esc(formatDate(l.createdAt))}</td><td>${esc(l.actorName||"-")}<div style="font-size:11px;color:#94a3b8">${esc(l.actorEmail||"")}</div></td><td>${esc(l.actorRole||"-")}</td><td><span class="badge badge-blue">${esc(actionLabel(l.action))}</span></td><td>${esc(categoryLabel(l.category))}</td><td>${esc(l.targetLabel||l.targetId||"-")}</td><td class="audit-detail">${esc(auditSummary(l))}</td></tr>`).join(""):`<tr><td colspan="7">目前沒有操作紀錄</td></tr>`;renderSimplePagination("auditPagination",total,auditCurrentPage,p=>{auditCurrentPage=p;renderAuditLogs()})}
function actionLabel(a){return {create:"新增",update:"修改",delete:"刪除",print:"列印",permission:"權限異動",login:"登入"}[a]||a||"-"}function categoryLabel(c){return {mailRecord:"郵件資料",department:"部門",user:"使用者權限",signSheet:"簽收單"}[c]||c||"-"}function auditSummary(l){const o=l.after||l.before||{};return Object.entries(o).filter(([k])=>!["createdTime","printedAt"].includes(k)).map(([k,v])=>`${k}:${v}`).join("；")||"-"}
function changeAuditPageSize(){auditPageSize=parseInt($("auditPageSize").value);auditCurrentPage=1;renderAuditLogs()} window.changeAuditPageSize=changeAuditPageSize;function resetAuditFilter(){$("auditSearch").value="";$("auditActionFilter").value="";auditCurrentPage=1;renderAuditLogs()} window.resetAuditFilter=resetAuditFilter;
async function loadLoginLogs(){if(!canAdmin())return;const snap=await getDocs(collection(db,"loginLogs"));loginLogs=[];snap.forEach(s=>loginLogs.push({id:s.id,...s.data()}));loginLogs.sort((a,b)=>getTime(b.loginTime)-getTime(a.loginTime));renderLoginLogs()} window.loadLoginLogs=loadLoginLogs;
function renderLoginLogs(){const total=Math.ceil(loginLogs.length/loginPageSize)||1;if(loginCurrentPage>total)loginCurrentPage=1;const page=loginLogs.slice((loginCurrentPage-1)*loginPageSize,loginCurrentPage*loginPageSize);$("loginCount").textContent=`(${loginLogs.length}筆)`;$("loginLogTable").innerHTML=page.length?page.map(l=>`<tr><td>${esc(formatDate(l.loginTime))}</td><td>${esc(l.name||"-")}</td><td>${esc(l.email||"-")}</td><td>${esc(l.role||"-")}</td></tr>`).join(""):`<tr><td colspan="4">目前沒有登入紀錄</td></tr>`;renderSimplePagination("loginPagination",total,loginCurrentPage,p=>{loginCurrentPage=p;renderLoginLogs()})}
function changeLoginPageSize(){loginPageSize=parseInt($("loginPageSize").value);loginCurrentPage=1;renderLoginLogs()} window.changeLoginPageSize=changeLoginPageSize;
function renderSimplePagination(id,total,current,cb){const area=$(id);if(!area)return;area.innerHTML="";if(total<=1)return;for(let i=1;i<=total;i++){const b=document.createElement("button");b.className="btn";b.textContent=i;b.style.background=i===current?"#2563eb":"#e2e8f0";b.style.color=i===current?"white":"#0f172a";b.onclick=()=>cb(i);area.appendChild(b)}}

["searchInput","typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].forEach(id=>document.addEventListener("input",e=>{if(e.target?.id===id){currentPage=1;renderMailTable()}}));document.addEventListener("change",e=>{if(["typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].includes(e.target?.id)){currentPage=1;renderMailTable()}if(["auditSearch","auditActionFilter"].includes(e.target?.id)){auditCurrentPage=1;renderAuditLogs()}});
async function googleLogin(){try{await signInWithPopup(auth,provider)}catch(e){alert(e.message)}} window.googleLogin=googleLogin;
async function logout(){sessionStorage.removeItem("mailLoginLogged");localStorage.removeItem("userRole");localStorage.removeItem("userEmail");localStorage.removeItem("userName");await signOut(auth)} window.logout=logout;

onAuthStateChanged(auth,async(user)=>{if(!user){$("loginPage").style.display="flex";$("systemArea").style.display="none";return}const snap=await getDocs(collection(db,"users"));let allow=false,found=null;snap.forEach(s=>{const d=s.data();if(d.email===user.email&&d.enabled===true){allow=true;found=d}});if(!allow){alert("此帳號未開通");await signOut(auth);return}currentRole=found.role||"user";currentUser=user.displayName||user.email;currentUserEmail=user.email;localStorage.setItem("userRole",currentRole);localStorage.setItem("userEmail",user.email);localStorage.setItem("userName",currentUser);if(!sessionStorage.getItem("mailLoginLogged")){await addDoc(collection(db,"loginLogs"),{name:currentUser,email:user.email,role:currentRole,loginTime:new Date()});sessionStorage.setItem("mailLoginLogged","true")}$("sidebarUserName").textContent=currentUser;$("sidebarUserEmail").textContent=user.email;$("loginPage").style.display="none";await Promise.all([loadDepartments(),loadUsers(),loadMailRecords(),loadLoginLogs()]);applyRoleAccess();restoreLastPage();$("systemArea").style.display="block";requestAnimationFrame(()=>$("systemArea").style.opacity="1");resetMailForm();if(window.lucide)lucide.createIcons();});
})();
