(async function initializeMailSystem(){
const { initializeApp } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-app.js");
const { getFirestore, collection, addDoc, getDocs, updateDoc, deleteDoc, doc } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-firestore.js");
const { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } = await import("https://www.gstatic.com/firebasejs/12.13.0/firebase-auth.js");

const firebaseConfig={apiKey:"AIzaSyCzvPwTbxc_Lg7peKRgP0zUrlmI6kkE0b4",authDomain:"seal-management-68465.firebaseapp.com",projectId:"seal-management-68465",storageBucket:"seal-management-68465.firebasestorage.app",messagingSenderId:"933578260928",appId:"1:933578260928:web:4c5f41252fd786e1bf0825",measurementId:"G-7RKPNF7BK9"};
const app=initializeApp(firebaseConfig); const db=getFirestore(app); const auth=getAuth(app); const provider=new GoogleAuthProvider();
const DEFAULT_MAIL_TYPES=["掛號","限掛","平信","黑貓宅急便","其他"];
let currentRole="",currentUser="系統使用者",currentUserEmail="";
let mailRecords=[],outgoingBatches=[],departmentList=[],mailTypeList=[],userList=[],auditLogs=[],loginLogs=[];
let currentPage=1,pageSize=10,auditCurrentPage=1,auditPageSize=25,loginCurrentPage=1,loginPageSize=10;
let selectedSheetRecords=[];

function $(id){return document.getElementById(id)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function todayStr(){return new Date().toISOString().slice(0,10)}
function ymStr(d=new Date()){return d.toISOString().slice(0,7)}
function formatDate(v){if(!v)return "-"; if(v.seconds)return new Date(v.seconds*1000).toLocaleString("zh-TW"); if(/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return String(v).replaceAll("-","/"); return new Date(v).toLocaleString("zh-TW")}
function getTime(v){if(!v)return 0;if(v.seconds)return v.seconds*1000;return new Date(v).getTime()||0}
function canAdmin(){return currentRole==="admin"}
function blockUserAdminAction(){ if(canAdmin()) return false; alert("此功能僅限 Admin 使用"); return true; }
function mailLabel(r){return r.trackingNo||r.receiver||r.id||"郵件"}

async function writeAuditLog({action,category,targetId="",targetLabel="",before=null,after=null}){try{await addDoc(collection(db,"mailAuditLogs"),{actorName:currentUser,actorEmail:currentUserEmail,actorRole:currentRole,action,category,targetId,targetLabel,before:compact(before),after:compact(after),createdAt:new Date()})}catch(e){console.error("audit fail",e)}}
function compact(data){if(!data)return null;const out={};Object.entries(data).forEach(([k,v])=>{if(k==="id")return;if(v===null||["string","number","boolean"].includes(typeof v))out[k]=v});return out}

function applyRoleAccess(){document.querySelectorAll(".admin-only").forEach(el=>el.style.display=canAdmin()?"":"none");$("systemMenuTitle").style.display=canAdmin()?"":"none"}
function toggleSidebar(){ $("sidebar").classList.toggle("collapsed") }
window.toggleSidebar=toggleSidebar;
function showPage(pageId,el){const adminPages=["deptPage","mailTypePage","permissionPage","auditLogPage","loginLogPage"];if(!canAdmin()&&adminPages.includes(pageId)){pageId="dashboardPage";el=document.querySelector('[onclick*=dashboardPage]')}document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(pageId)?.classList.remove("hidden");document.querySelectorAll(".menu-item").forEach(i=>i.classList.remove("active"));if(el)el.classList.add("active");localStorage.setItem("mailLastPage",pageId);if(pageId==="deptPage"){loadDepartments().catch(error=>{console.error("部門重新載入失敗",error);renderDepartmentMaintenanceError(error);});}if(pageId==="mailTypePage")loadMailTypes();if(window.lucide)lucide.createIcons();}
window.showPage=showPage;
function restoreLastPage(){const last=localStorage.getItem("mailLastPage")||"dashboardPage";const menu=document.querySelector(`[onclick*="${last}"]`)||document.querySelector('[onclick*=dashboardPage]');showPage(last,menu)}

function currentMailTypes(){return mailTypeList.length?mailTypeList.map(type=>type.name):DEFAULT_MAIL_TYPES}
function renderDropdowns(){const types=currentMailTypes(),mailTypeValue=$("mailType")?.value||"",typeFilterValue=$("typeFilter")?.value||"",typeOptions=types.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("");if($("mailType")){$("mailType").innerHTML=typeOptions;$("mailType").value=types.includes(mailTypeValue)?mailTypeValue:(types[0]||"")}if($("typeFilter")){$("typeFilter").innerHTML=`<option value="">全部類型</option>`+typeOptions;$("typeFilter").value=types.includes(typeFilterValue)?typeFilterValue:""}const deptOptions=departmentList.map(d=>`<option value="${esc(d.name)}">${esc(d.name)}</option>`).join("");if($("department"))$("department").innerHTML=`<option value="">請選擇</option>`+deptOptions;if($("deptFilter"))$("deptFilter").innerHTML=`<option value="">全部部門</option>`+deptOptions;}

async function loadDepartments(){
try{
const snap=await getDocs(collection(db,"departments"));
departmentList=[];
snap.forEach(s=>{
const data=s.data()||{};
const name=(data.name||"").trim();
if(name){
departmentList.push({id:s.id,...data,name,sortOrder:Number(data.sortOrder||999)});
}
});
departmentList.sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,"zh-Hant"));
window.mailDepartmentList=departmentList;
renderDropdowns();
renderDepartmentMaintenance();
return departmentList;
}catch(error){
console.error("讀取共用部門 departments 失敗",error);
renderDepartmentMaintenanceError(error);
throw error;
}
}
async function loadMailTypes(){
try{
const snap=await getDocs(collection(db,"mailTypes"));
mailTypeList=[];
snap.forEach(s=>{
const data=s.data()||{},name=(data.name||"").trim();
if(name)mailTypeList.push({id:s.id,...data,name,sortOrder:Number(data.sortOrder||999)});
});
mailTypeList.sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,"zh-Hant"));
if(!mailTypeList.length&&canAdmin()){
for(let i=0;i<DEFAULT_MAIL_TYPES.length;i++)await addDoc(collection(db,"mailTypes"),{name:DEFAULT_MAIL_TYPES[i],sortOrder:i+1});
return loadMailTypes();
}
renderDropdowns();
renderMailTypeMaintenance();
return mailTypeList;
}catch(error){
console.error("讀取郵件類型 mailTypes 失敗",error);
mailTypeList=[];
renderDropdowns();
renderMailTypeMaintenanceError(error);
return [];
}
}
async function loadUsers(){const snap=await getDocs(collection(db,"users"));userList=[];snap.forEach(s=>userList.push({id:s.id,...s.data()}));renderUserList()}
async function loadMailRecords(){const snap=await getDocs(collection(db,"mailRecords"));mailRecords=[];snap.forEach(s=>mailRecords.push({id:s.id,...s.data()}));mailRecords.sort((a,b)=>(getTime(b.createdTime)||Date.parse(b.receiveDate||0))-(getTime(a.createdTime)||Date.parse(a.receiveDate||0)));renderDashboard();renderMailTable();renderSheetPage();}
async function loadOutgoingBatches(){const snap=await getDocs(collection(db,"outgoingMailBatches"));outgoingBatches=[];snap.forEach(s=>outgoingBatches.push({id:s.id,...s.data()}));outgoingBatches.sort((a,b)=>(getTime(b.createdTime)||Date.parse(b.sendDate||0))-(getTime(a.createdTime)||Date.parse(a.sendDate||0)));renderOutgoingBatchList();renderMailTable();}

function resetMailForm(){["mailId","trackingNo","sender","receiver","remark"].forEach(id=>$(id).value="");$("receiveDate").value=todayStr();const types=currentMailTypes();$("mailType").value=types.includes("掛號")?"掛號":(types[0]||"");$("department").value="";}
window.resetMailForm=resetMailForm;
function prepareNextMailEntry(data){["mailId","trackingNo","sender","receiver","remark"].forEach(id=>$(id).value="");$("receiveDate").value=data.receiveDate;$("mailType").value=data.mailType;$("department").value=data.department;$("trackingNo").focus()}
async function saveMailRecord(){const id=$("mailId").value;const data={receiveDate:$("receiveDate").value,mailType:$("mailType").value,trackingNo:$("trackingNo").value.trim(),sender:$("sender").value.trim(),department:$("department").value,receiver:$("receiver").value.trim(),remark:$("remark").value.trim()};if(!data.receiveDate||!data.mailType||!data.sender||!data.department||!data.receiver){alert("請填寫收件日期、郵件類型、寄件人、收件部門、收件人");return}if(id){const before=mailRecords.find(r=>r.id===id);await updateDoc(doc(db,"mailRecords",id),data);await writeAuditLog({action:"update",category:"mailRecord",targetId:id,targetLabel:mailLabel(data),before,after:{...before,...data}});alert("修改成功");resetMailForm()}else{const ref=await addDoc(collection(db,"mailRecords"),{...data,printed:false,createdBy:currentUser,createdByEmail:currentUserEmail,createdTime:new Date()});await writeAuditLog({action:"create",category:"mailRecord",targetId:ref.id,targetLabel:mailLabel(data),after:{...data,printed:false}});alert("登錄成功，可繼續登錄同部門郵件");prepareNextMailEntry(data)}await loadMailRecords();}
window.saveMailRecord=saveMailRecord;
function editMail(id){const r=mailRecords.find(x=>x.id===id);if(!r)return;showPage("registerPage",document.querySelector('[onclick*=registerPage]'));$("mailId").value=id;$("receiveDate").value=r.receiveDate||todayStr();if(r.mailType&&!currentMailTypes().includes(r.mailType))$("mailType").insertAdjacentHTML("beforeend",`<option value="${esc(r.mailType)}">${esc(r.mailType)}（歷史類型）</option>`);$("mailType").value=r.mailType||currentMailTypes()[0]||"";$("trackingNo").value=r.trackingNo||"";$("sender").value=r.sender||"";$("department").value=r.department||"";$("receiver").value=r.receiver||"";$("remark").value=r.remark||"";}
window.editMail=editMail;
async function deleteMail(id){const r=mailRecords.find(x=>x.id===id);if(!confirm("確定刪除此筆郵件資料？"))return;await deleteDoc(doc(db,"mailRecords",id));await writeAuditLog({action:"delete",category:"mailRecord",targetId:id,targetLabel:mailLabel(r),before:r});await loadMailRecords();}
window.deleteMail=deleteMail;
async function togglePrinted(id,printed){const r=mailRecords.find(x=>x.id===id);await updateDoc(doc(db,"mailRecords",id),{printed:!printed,printedAt:!printed?new Date():null,printedBy:!printed?currentUser:""});await writeAuditLog({action:"update",category:"mailRecord",targetId:id,targetLabel:mailLabel(r),before:r,after:{...r,printed:!printed}});await loadMailRecords();}
window.togglePrinted=togglePrinted;

function renderDashboard(){const today=todayStr(),month=ymStr();const todayRecords=mailRecords.filter(r=>r.receiveDate===today);$("kpiToday").textContent=todayRecords.length;$("kpiPendingPrint").textContent=mailRecords.filter(r=>!r.printed).length;$("kpiMonth").textContent=mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)).length;$("kpiRegistered").textContent=mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)&&["掛號","限掛"].includes(r.mailType)).length;renderSummary("todayDeptSummary",groupCount(todayRecords,"department"));renderSummary("typeSummary",groupCount(mailRecords.filter(r=>(r.receiveDate||"").startsWith(month)),"mailType"));}
function groupCount(list,key){const m={};list.forEach(r=>{const k=r[key]||"未分類";m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function renderSummary(id,rows){$(id).innerHTML=rows.length?rows.map(([k,v])=>`<div class="summary-item"><strong>${esc(k)}</strong><span>${v} 件</span></div>`).join(""):`<div class="summary-item"><strong>目前無資料</strong><span>0 件</span></div>`}

function getFilteredRecords(){const kw=($("searchInput")?.value||"").toLowerCase();const type=$("typeFilter")?.value||"";const dept=$("deptFilter")?.value||"";const printed=$("printedFilter")?.value||"";const start=$("dateStart")?.value||"";const end=$("dateEnd")?.value||"";return mailRecords.filter(r=>{const text=[r.trackingNo,r.sender,r.department,r.receiver,r.remark,r.mailType].join(" ").toLowerCase();return (!kw||text.includes(kw))&&(!type||r.mailType===type)&&(!dept||r.department===dept)&&(!printed||(printed==="printed"?r.printed:!r.printed))&&(!start||r.receiveDate>=start)&&(!end||r.receiveDate<=end)})}
function getFilteredOutgoingRecords(){const kw=($("searchInput")?.value||"").toLowerCase();const type=$("typeFilter")?.value||"";const start=$("dateStart")?.value||"";const end=$("dateEnd")?.value||"";return outgoingBatches.flatMap(batch=>(batch.items||[]).map((item,index)=>({...item,batchId:batch.id,batchNo:batch.batchNo||batch.id,sendDate:batch.sendDate,mailType:batch.mailType,senderName:batch.senderName,itemNo:index+1}))).filter(r=>{const text=[r.trackingNo,r.receiverName,r.address,r.senderName,r.batchNo,r.mailType].join(" ").toLowerCase();return (!kw||text.includes(kw))&&(!type||r.mailType===type)&&(!start||r.sendDate>=start)&&(!end||r.sendDate<=end)})}
function syncHistoryFilterMode(outgoing){$("deptFilter").closest(".filter-card").style.display=outgoing?"none":"";$("printedFilter").closest(".filter-card").style.display=outgoing?"none":"";const types=outgoing?["掛號函件","限時掛號","快捷郵件"]:currentMailTypes(),current=$("typeFilter").value;$("typeFilter").innerHTML=`<option value="">全部類型</option>`+types.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("");$("typeFilter").value=types.includes(current)?current:""}
function renderMailTable(){const table=$("mailTable");if(!table)return;const outgoing=$("directionFilter")?.value==="outgoing";syncHistoryFilterMode(outgoing);const filtered=outgoing?getFilteredOutgoingRecords():getFilteredRecords();$("recordCount").textContent=filtered.length;const total=Math.ceil(filtered.length/pageSize)||1;if(currentPage>total)currentPage=1;const pageRows=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);const head=table.closest("table").querySelector("thead");if(outgoing){head.innerHTML="<tr><th>交寄日期</th><th>類型</th><th>掛號號碼</th><th>收件人</th><th>寄達地址</th><th>寄件人</th><th>批次</th><th>操作</th></tr>";table.innerHTML=pageRows.length?pageRows.map(r=>`<tr><td>${esc(formatDate(r.sendDate))}</td><td>${esc(r.mailType)}</td><td>${esc(r.trackingNo||"-")}</td><td>${esc(r.receiverName)}</td><td class="outgoing-address-cell">${esc(r.address)}</td><td>${esc(r.senderName||"-")}</td><td>${esc(r.batchNo)}</td><td><button class="btn btn-gray" onclick="editOutgoingBatch('${r.batchId}')">開啟批次</button></td></tr>`).join(""):`<tr><td colspan="8">目前沒有符合條件的寄件資料</td></tr>`}else{head.innerHTML="<tr><th>收件日期</th><th>類型</th><th>掛號 / 單號</th><th>寄件人</th><th>部門</th><th>收件人</th><th>狀態</th><th>操作</th></tr>";table.innerHTML=pageRows.length?pageRows.map(r=>`<tr><td>${esc(formatDate(r.receiveDate))}</td><td>${esc(r.mailType)}</td><td>${esc(r.trackingNo||"-")}</td><td>${esc(r.sender)}</td><td>${esc(r.department)}</td><td>${esc(r.receiver)}</td><td>${r.printed?'<span class="badge badge-green">已列印</span>':'<span class="badge badge-yellow">未列印</span>'}</td><td><button class="btn btn-gray" onclick="editMail('${r.id}')">編輯</button> <button class="btn btn-gray" onclick="togglePrinted('${r.id}',${!!r.printed})">${r.printed?'改未列印':'標記列印'}</button> <button class="btn btn-red" onclick="deleteMail('${r.id}')">刪除</button></td></tr>`).join(""):`<tr><td colspan="8">目前沒有符合條件的郵件資料</td></tr>`}renderPagination(total)}
function renderPagination(total){const area=$("paginationArea");if(!area)return;area.innerHTML="";if(total<=1)return;for(let i=1;i<=total;i++){const b=document.createElement("button");b.className="btn";b.textContent=i;b.style.background=i===currentPage?"#2563eb":"#e2e8f0";b.style.color=i===currentPage?"white":"#0f172a";b.onclick=()=>{currentPage=i;renderMailTable()};area.appendChild(b)}}
function changePageSize(){pageSize=parseInt($("pageSizeSelect").value);currentPage=1;renderMailTable()} window.changePageSize=changePageSize;
function resetHistoryFilter(){["searchInput","typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].forEach(id=>$(id).value="");currentPage=1;renderMailTable()} window.resetHistoryFilter=resetHistoryFilter;
function toggleAdvancedFilter(){const p=$("advancedFilter"),t=$("filterToggleText");p.classList.toggle("show");t.textContent=p.classList.contains("show")?"收合篩選":"進階篩選"} window.toggleAdvancedFilter=toggleAdvancedFilter;
function exportExcel(){const outgoing=$("directionFilter")?.value==="outgoing";const data=outgoing?getFilteredOutgoingRecords().map(r=>({交寄日期:formatDate(r.sendDate),郵件類型:r.mailType,掛號號碼:r.trackingNo||"",收件人:r.receiverName,寄達地址:r.address,寄件人:r.senderName||"",批次編號:r.batchNo})):getFilteredRecords().map(r=>({收件日期:formatDate(r.receiveDate),郵件類型:r.mailType,掛號單號:r.trackingNo||"",寄件人:r.sender,收件部門:r.department,收件人:r.receiver,備註:r.remark||"",列印狀態:r.printed?"已列印":"未列印",登錄人:r.createdBy||""}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,outgoing?"大宗寄件紀錄":"郵件簽收紀錄");XLSX.writeFile(wb,outgoing?"大宗寄件紀錄.xlsx":"郵件簽收紀錄.xlsx")} window.exportExcel=exportExcel;

function renderSheetPage(){if(!$("sheetDeptList"))return;if(!$("sheetDate").value)$("sheetDate").value=todayStr();const date=$("sheetDate").value;const only=$("sheetOnlyUnprinted").checked;const rows=mailRecords.filter(r=>(!date||r.receiveDate===date)&&(!only||!r.printed));const grouped=groupCount(rows,"department");$("sheetDeptList").innerHTML=grouped.length?grouped.map(([dept,count])=>`<label class="dept-check-card"><div><strong>${esc(dept)}</strong><br><span>${count} 件郵件</span></div><input type="checkbox" class="sheet-dept-check" value="${esc(dept)}"></label>`).join(""):`<div class="summary-item"><strong>沒有可產生簽收單的郵件</strong><span>0 件</span></div>`;}
window.renderSheetPage=renderSheetPage;
function selectAllSheetDepartments(flag){document.querySelectorAll(".sheet-dept-check").forEach(c=>c.checked=flag)} window.selectAllSheetDepartments=selectAllSheetDepartments;
function generateSignSheet(){const depts=[...document.querySelectorAll(".sheet-dept-check:checked")].map(c=>c.value);if(!depts.length){alert("請先選擇至少一個部門");return}const date=$("sheetDate").value;const only=$("sheetOnlyUnprinted").checked;selectedSheetRecords=mailRecords.filter(r=>(!date||r.receiveDate===date)&&depts.includes(r.department)&&(!only||!r.printed));if(!selectedSheetRecords.length){alert("選取部門沒有可列印郵件");return}$("signSheetPreview").classList.remove("empty-preview");$("signSheetPreview").innerHTML=buildSignSheetHtml(selectedSheetRecords,date);}
window.generateSignSheet=generateSignSheet;
function buildSignSheetHtml(rows,date){const grouped={};rows.forEach(r=>{(grouped[r.department] ||= []).push(r)});let html=`<div class="sheet-doc"><div class="sheet-header"><h1>環興科技股份有限公司</h1><h2>郵件簽收單</h2></div><div class="sheet-meta"><div>收件日期：${esc(formatDate(date))}</div><div>列印時間：${esc(new Date().toLocaleString("zh-TW"))}</div><div>總件數：${rows.length} 件</div></div>`;Object.entries(grouped).forEach(([dept,list])=>{html+=`<div class="sheet-dept"><div class="sheet-dept-title">${esc(dept)}（${list.length}件）</div><table class="sheet-table"><thead><tr><th style="width:52px;">序號</th><th>類型</th><th>掛號 / 單號</th><th>寄件人</th><th>收件人</th><th style="width:110px;">簽收</th></tr></thead><tbody>`;list.forEach((r,i)=>{html+=`<tr><td style="text-align:center;">${i+1}</td><td>${esc(r.mailType)}</td><td>${esc(r.trackingNo||"-")}</td><td>${esc(r.sender)}</td><td>${esc(r.receiver)}</td><td></td></tr>`});html+=`</tbody></table><div class="signature-row"><div>簽收人：________________</div><div>簽收日期：________________</div></div></div>`});return html+`</div>`}
async function markSelectedAsPrinted(){if(!selectedSheetRecords.length){alert("請先產生簽收單");return}if(!confirm(`確定將 ${selectedSheetRecords.length} 筆郵件標記為已列印？`))return;const batchNo=`MAIL-${Date.now()}`;for(const r of selectedSheetRecords){await updateDoc(doc(db,"mailRecords",r.id),{printed:true,printBatchNo:batchNo,printedAt:new Date(),printedBy:currentUser})}await writeAuditLog({action:"print",category:"signSheet",targetLabel:batchNo,after:{count:selectedSheetRecords.length,departments:[...new Set(selectedSheetRecords.map(r=>r.department))].join(",")}});alert("已標記為已列印");selectedSheetRecords=[];await loadMailRecords();}
window.markSelectedAsPrinted=markSelectedAsPrinted;

function outgoingRowHtml(item={}){return `<tr class="outgoing-entry-row"><td class="outgoing-seq"></td><td><input data-field="trackingNo" value="${esc(item.trackingNo||"")}"></td><td><input data-field="receiverName" value="${esc(item.receiverName||"")}"></td><td><input data-field="address" value="${esc(item.address||"")}"></td><td><input type="checkbox" data-field="returnReceipt" ${item.returnReceipt?"checked":""}></td><td><input type="checkbox" data-field="printedMatter" ${item.printedMatter?"checked":""}></td><td><input data-field="weight" value="${esc(item.weight||"")}"></td><td><input data-field="postage" value="${esc(item.postage||"")}"></td><td><input data-field="contents" value="${esc(item.contents||"")}"></td><td><button class="btn btn-red outgoing-remove-btn" type="button" onclick="removeOutgoingRow(this)">刪除</button></td></tr>`}
function refreshOutgoingRows(){document.querySelectorAll(".outgoing-entry-row").forEach((row,index)=>row.querySelector(".outgoing-seq").textContent=index+1);$("outgoingItemCount").textContent=`共 ${document.querySelectorAll(".outgoing-entry-row").length} 件`}
function nextTrackingNo(value){const text=String(value||"").trim();if(!/^\d+$/.test(text))return "";return String(BigInt(text)+1n).padStart(text.length,"0")}
function addOutgoingRow(item){const rows=[...document.querySelectorAll(".outgoing-entry-row")];if(rows.length>=20){alert("郵局範本每張最多 20 件");return}const data=item||{},previousTracking=rows.at(-1)?.querySelector('[data-field="trackingNo"]')?.value||"";if(!data.trackingNo)data.trackingNo=nextTrackingNo(previousTracking);$("outgoingEntryRows").insertAdjacentHTML("beforeend",outgoingRowHtml(data));refreshOutgoingRows();const newRow=document.querySelector(".outgoing-entry-row:last-child");(data.trackingNo?newRow?.querySelector('[data-field="receiverName"]'):newRow?.querySelector('[data-field="trackingNo"]'))?.focus()} window.addOutgoingRow=addOutgoingRow;
function removeOutgoingRow(btn){if(document.querySelectorAll(".outgoing-entry-row").length<=1){alert("至少保留一列");return}btn.closest("tr").remove();refreshOutgoingRows()} window.removeOutgoingRow=removeOutgoingRow;
function getOutgoingItems(){return [...document.querySelectorAll(".outgoing-entry-row")].map(row=>{const get=name=>row.querySelector(`[data-field="${name}"]`);return {trackingNo:get("trackingNo").value.trim(),receiverName:get("receiverName").value.trim(),address:get("address").value.trim(),returnReceipt:get("returnReceipt").checked,printedMatter:get("printedMatter").checked,weight:get("weight").value.trim(),postage:get("postage").value.trim(),contents:get("contents").value.trim()}}).filter(item=>item.trackingNo||item.receiverName||item.address)}
function prepareOutgoingPage(){if(!$("outgoingDate").value||!$("outgoingEntryRows").children.length)resetOutgoingForm();else refreshOutgoingRows();renderOutgoingBatchList()}
window.prepareOutgoingPage=prepareOutgoingPage;
function startNewOutgoingForm(){const hasInput=getOutgoingItems().length>0;if(hasInput&&!confirm("目前填寫的寄件明細將會清除，確定要清空重填嗎？"))return;resetOutgoingForm()} window.startNewOutgoingForm=startNewOutgoingForm;
function resetOutgoingForm(){["outgoingBatchId","outgoingRepresentative","outgoingSenderAddress","outgoingSenderPhone"].forEach(id=>$(id).value="");$("outgoingDate").value=todayStr();$("outgoingType").value="掛號函件";$("outgoingSenderName").value=localStorage.getItem("outgoingSenderName")||"";$("outgoingRepresentative").value=localStorage.getItem("outgoingRepresentative")||"";$("outgoingSenderAddress").value=localStorage.getItem("outgoingSenderAddress")||"";$("outgoingSenderPhone").value=localStorage.getItem("outgoingSenderPhone")||"";$("outgoingEntryRows").innerHTML=outgoingRowHtml();refreshOutgoingRows()} window.resetOutgoingForm=resetOutgoingForm;
function outgoingFormData(){return {sendDate:$("outgoingDate").value,mailType:$("outgoingType").value,senderName:$("outgoingSenderName").value.trim(),representative:$("outgoingRepresentative").value.trim(),senderAddress:$("outgoingSenderAddress").value.trim(),senderPhone:$("outgoingSenderPhone").value.trim(),items:getOutgoingItems()}}
function validateOutgoing(data){if(!data.sendDate||!data.senderName){alert("請填寫交寄日期與公司名稱");return false}if(!data.items.length){alert("請至少填寫一筆寄件資料");return false}if(!data.items[0].trackingNo){alert("請填寫第一筆掛號號碼，系統會用它建立寄件紀錄編號");return false}const invalid=data.items.findIndex(item=>!item.receiverName||!item.address);if(invalid>=0){alert(`第 ${invalid+1} 筆請填寫收件人姓名與寄達地址`);return false}return true}
function makeOutgoingBatchNo(data){return `OUT-${data.sendDate.replaceAll("-","")}-${data.items[0].trackingNo}`}
async function saveOutgoingBatch(){const id=$("outgoingBatchId").value,data=outgoingFormData();if(!validateOutgoing(data))return;["outgoingSenderName","outgoingRepresentative","outgoingSenderAddress","outgoingSenderPhone"].forEach(id=>localStorage.setItem(id,$(id).value.trim()));try{if(id){const before=outgoingBatches.find(b=>b.id===id);await updateDoc(doc(db,"outgoingMailBatches",id),{...data,updatedTime:new Date(),updatedBy:currentUser});await writeAuditLog({action:"update",category:"outgoingMailBatch",targetId:id,targetLabel:before?.batchNo||id,before,after:data})}else{const batchNo=makeOutgoingBatchNo(data);if(outgoingBatches.some(batch=>batch.batchNo===batchNo)){alert(`寄件紀錄編號 ${batchNo} 已存在，請確認交寄日期或第一筆掛號號碼`);return}const ref=await addDoc(collection(db,"outgoingMailBatches"),{...data,batchNo,createdTime:new Date(),createdBy:currentUser,createdByEmail:currentUserEmail});$("outgoingBatchId").value=ref.id;await writeAuditLog({action:"create",category:"outgoingMailBatch",targetId:ref.id,targetLabel:batchNo,after:{...data,batchNo,itemCount:data.items.length}})}await loadOutgoingBatches();alert(id?"寄件資料已更新":"寄件資料已儲存")}catch(error){console.error(error);alert("儲存失敗：" + (error?.message||error))}} window.saveOutgoingBatch=saveOutgoingBatch;
function editOutgoingBatch(id){const batch=outgoingBatches.find(b=>b.id===id);if(!batch)return;showPage("outgoingPage",document.querySelector('[onclick*=outgoingPage]'));$("outgoingBatchId").value=batch.id;$("outgoingDate").value=batch.sendDate||todayStr();$("outgoingType").value=batch.mailType||"掛號函件";$("outgoingSenderName").value=batch.senderName||"";$("outgoingRepresentative").value=batch.representative||"";$("outgoingSenderAddress").value=batch.senderAddress||"";$("outgoingSenderPhone").value=batch.senderPhone||"";$("outgoingEntryRows").innerHTML=(batch.items||[]).map(outgoingRowHtml).join("")||outgoingRowHtml();refreshOutgoingRows()} window.editOutgoingBatch=editOutgoingBatch;
async function deleteOutgoingBatch(id){const batch=outgoingBatches.find(b=>b.id===id);if(!confirm(`確定刪除寄件批次 ${batch?.batchNo||""}？`))return;await deleteDoc(doc(db,"outgoingMailBatches",id));await writeAuditLog({action:"delete",category:"outgoingMailBatch",targetId:id,targetLabel:batch?.batchNo||id,before:batch});if($("outgoingBatchId").value===id)resetOutgoingForm();await loadOutgoingBatches()} window.deleteOutgoingBatch=deleteOutgoingBatch;
function renderOutgoingBatchList(){const area=$("outgoingBatchList");if(!area)return;area.innerHTML=outgoingBatches.length?outgoingBatches.slice(0,10).map(batch=>`<div class="maintenance-item"><div><strong>${esc(batch.batchNo||batch.id)}</strong><br><span>${esc(formatDate(batch.sendDate))} · ${esc(batch.mailType)} · ${batch.items?.length||0} 件</span></div><div class="maintenance-actions"><button class="btn btn-gray" onclick="editOutgoingBatch('${batch.id}')">開啟</button><button class="btn btn-red" onclick="deleteOutgoingBatch('${batch.id}')">刪除</button></div></div>`).join(""):`<p class="page-desc">目前沒有大宗寄件批次。</p>`}
function rocDate(date){const [y,m,d]=(date||todayStr()).split("-").map(Number);return `中華民國 ${y-1911} 年 ${m} 月 ${d} 日`}
function buildOutgoingPrintHtml(data){const rows=[...data.items];while(rows.length<20)rows.push({});const body=rows.map((item,index)=>`<tr><td>${index+1}</td><td>${esc(item.trackingNo||"")}</td><td>${esc(item.receiverName||"")}</td><td>${esc(item.address||"")}</td><td>${item.returnReceipt?"✓":""}</td><td>${item.printedMatter?"✓":""}</td><td>${esc(item.weight||"")}</td><td>${esc(item.postage||"")}</td><td>${esc(item.contents||"")}</td></tr>`).join("");return `<div class="postal-form"><div class="postal-code-box">□□□□□□　□□<br><small>收寄局碼　郵件種類碼（由收寄局填寫）</small></div><div class="postal-stamp">郵局郵戳</div><div class="postal-title">中 華 民 國 郵 政<h1>交寄大宗 ${esc(data.mailType)} 執據</h1></div><div class="postal-date">${rocDate(data.sendDate)}</div><div class="postal-sender"><div>寄件人名稱：${esc(data.senderName)}</div><div>寄件人代表：${esc(data.representative)}</div><div>詳細地址：${esc(data.senderAddress)}</div><div>電話號碼：${esc(data.senderPhone)}</div></div><table class="postal-table"><thead><tr><th rowspan="2">順序<br>號碼</th><th rowspan="2">掛號號碼</th><th colspan="2">收件人</th><th rowspan="2">是否<br>回執</th><th rowspan="2">是否<br>印刷物</th><th rowspan="2">重量</th><th rowspan="2">郵資</th><th rowspan="2">內裝物品名稱</th></tr><tr><th>姓名</th><th>寄達地名（或地址）</th></tr></thead><tbody>${body}</tbody></table><div class="postal-footer"><div>上開 ${esc(data.mailType)} 共 ${data.items.length} 件照收無誤</div><div>郵資共計 __________ 元　　經辦員簽署 __________________</div><div>寄件人簽章：__________________</div></div><div class="postal-note">本表依「交寄大宗限時掛號及掛號函件執據存根2聯單」欄位製作；列印 2 份作為執據及存根。</div></div>`}
function printOutgoingForm(){const data=outgoingFormData();if(!validateOutgoing(data))return;$("outgoingPrintArea").innerHTML=buildOutgoingPrintHtml(data)+buildOutgoingPrintHtml(data);document.body.classList.add("printing-outgoing");window.print();setTimeout(()=>document.body.classList.remove("printing-outgoing"),500)} window.printOutgoingForm=printOutgoingForm;
const WORD_NS="http://schemas.openxmlformats.org/wordprocessingml/2006/main";
function wordTextNodes(parent){return [...parent.getElementsByTagNameNS(WORD_NS,"t")]}
function setWordParagraphText(paragraph,text){const nodes=wordTextNodes(paragraph);if(nodes.length){nodes[0].textContent=text;nodes[0].setAttributeNS("http://www.w3.org/XML/1998/namespace","xml:space","preserve");nodes.slice(1).forEach(node=>node.textContent="");return}const run=paragraph.ownerDocument.createElementNS(WORD_NS,"w:r"),textNode=paragraph.ownerDocument.createElementNS(WORD_NS,"w:t");textNode.setAttributeNS("http://www.w3.org/XML/1998/namespace","xml:space","preserve");textNode.textContent=text;run.appendChild(textNode);paragraph.appendChild(run)}
function setWordCellText(cell,text){const paragraph=cell.getElementsByTagNameNS(WORD_NS,"p")[0];if(!paragraph)return;setWordParagraphText(paragraph,text)}
function fillWordHeader(xmlDoc,data){const paragraphs=[...xmlDoc.getElementsByTagNameNS(WORD_NS,"p")].filter(p=>!p.getElementsByTagNameNS(WORD_NS,"p").length);const dateParts=(data.sendDate||todayStr()).split("-").map(Number),rocYear=dateParts[0]-1911;const allTexts=wordTextNodes(xmlDoc);for(let i=0;i<allTexts.length-6;i++){if(allTexts[i].textContent==="中華民國"&&allTexts[i+2]?.textContent==="年"&&allTexts[i+4]?.textContent==="月"){allTexts[i+1].textContent=` ${rocYear} `;allTexts[i+3].textContent=` ${dateParts[1]} `;allTexts[i+5].textContent=` ${dateParts[2]} `;break}}const nameParagraph=paragraphs.find(p=>wordTextNodes(p).map(n=>n.textContent).join("").includes("名稱："));if(nameParagraph)setWordParagraphText(nameParagraph,`　　　　　名稱：${data.senderName}`);const detailParagraph=paragraphs.find(p=>{const text=wordTextNodes(p).map(n=>n.textContent).join("");return text.includes("寄件人代表")&&text.includes("詳細地址")&&text.includes("電話號碼")});if(detailParagraph)setWordParagraphText(detailParagraph,`寄件人代表　${data.representative||""}　　　詳細地址：${data.senderAddress||""}　　　電話號碼：${data.senderPhone||""}`)}
function fillWordItems(xmlDoc,items){const table=xmlDoc.getElementsByTagNameNS(WORD_NS,"tbl")[0];if(!table)throw new Error("原始 Word 找不到明細表格");const rows=[...table.getElementsByTagNameNS(WORD_NS,"tr")];for(let index=0;index<20;index++){const row=rows[index+2],item=items[index]||{};if(!row)continue;const cells=[...row.getElementsByTagNameNS(WORD_NS,"tc")];const values=[String(index+1),item.trackingNo||"",item.receiverName||"",item.address||"",item.returnReceipt?"✓":"",item.printedMatter?"✓":"",item.weight||"",item.postage||"",item.contents||""];values.forEach((value,cellIndex)=>{if(cells[cellIndex])setWordCellText(cells[cellIndex],value)})}}
function updateWordCount(xmlDoc,data){const paragraphs=[...xmlDoc.getElementsByTagNameNS(WORD_NS,"p")].filter(p=>!p.getElementsByTagNameNS(WORD_NS,"p").length);paragraphs.forEach(p=>{const text=wordTextNodes(p).map(n=>n.textContent).join("");if(text.includes("件照收無誤")&&text.includes("共"))setWordParagraphText(p,`     ${data.mailType} / 共 ${data.items.length} 件照收無誤`)})}
async function downloadOutgoingWord(){const data=outgoingFormData();if(!validateOutgoing(data))return;if(!window.JSZip){alert("Word 套表元件尚未載入，請確認網路連線後重新整理");return}try{const templateUrl=`./交寄大宗限時掛號及掛號函件執據存根2聯單_原始範本.docx?refresh=${Date.now()}`,response=await fetch(templateUrl,{cache:"no-store"});if(!response.ok)throw new Error(`無法讀取 Word 範本（${response.status}）`);const zip=await JSZip.loadAsync(await response.arrayBuffer()),documentFile=zip.file("word/document.xml");if(!documentFile)throw new Error("Word 範本缺少 document.xml");const parser=new DOMParser(),xmlDoc=parser.parseFromString(await documentFile.async("string"),"application/xml");if(xmlDoc.getElementsByTagName("parsererror").length)throw new Error("Word 範本 XML 解析失敗");fillWordHeader(xmlDoc,data);fillWordItems(xmlDoc,data.items);updateWordCount(xmlDoc,data);zip.file("word/document.xml",new XMLSerializer().serializeToString(xmlDoc));const blob=await zip.generateAsync({type:"blob",mimeType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",compression:"DEFLATE"}),url=URL.createObjectURL(blob),link=document.createElement("a"),generatedAt=new Date().toLocaleTimeString("zh-TW",{hour12:false}).replaceAll(":","");link.href=url;link.download=`大宗掛號執據_${data.sendDate}_${generatedAt}.docx`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){console.error(error);alert("產生原版 Word 失敗：" + (error?.message||error))}} window.downloadOutgoingWord=downloadOutgoingWord;

function renderDepartmentMaintenance(){
const area=$("deptListArea");
if(!area)return;
if(!departmentList.length){
area.innerHTML="<p class='page-desc'>目前共用部門主檔 departments 尚無資料，或尚未成功載入。</p>";
return;
}
area.innerHTML=`<div class="dept-sync-note">目前讀取共用主檔：<b>departments</b>，共 <b>${departmentList.length}</b> 個部門。</div>`+
departmentList.map(d=>`<div class="maintenance-item"><div><strong>${esc(d.name)}</strong><br><span>排序：${esc(d.sortOrder)}</span></div><div class="maintenance-actions"><button class="btn btn-gray" onclick="moveDept('${d.id}',-1)">上移</button><button class="btn btn-gray" onclick="moveDept('${d.id}',1)">下移</button><button class="btn btn-red" onclick="deleteDepartment('${d.id}')">刪除</button></div></div>`).join("");
}
function renderDepartmentMaintenanceError(error){
const area=$("deptListArea");
if(!area)return;
area.innerHTML=`<div class="error-box"><b>部門讀取失敗</b><br>${esc(error?.message||error||"未知錯誤")}<br><span>請確認 Firestore Rules 已允許 departments 讀取。</span></div>`;
}
async function addDepartment(){if(blockUserAdminAction())return;const name=$("newDept").value.trim(),sortOrder=parseInt($("newDeptOrder").value||departmentList.length+1);if(!name){alert("請輸入部門名稱");return}const ref=await addDoc(collection(db,"departments"),{name,sortOrder});await writeAuditLog({action:"create",category:"department",targetId:ref.id,targetLabel:name,after:{name,sortOrder}});$("newDept").value="";$("newDeptOrder").value="";await loadDepartments()} window.addDepartment=addDepartment;
async function deleteDepartment(id){if(blockUserAdminAction())return;const d=departmentList.find(x=>x.id===id);if(!confirm(`確定刪除部門 ${d?.name||""}？`))return;await deleteDoc(doc(db,"departments",id));await writeAuditLog({action:"delete",category:"department",targetId:id,targetLabel:d?.name||id,before:d});await loadDepartments()} window.deleteDepartment=deleteDepartment;
async function moveDept(id,dir){if(blockUserAdminAction())return;const idx=departmentList.findIndex(d=>d.id===id);const ni=idx+dir;if(idx<0||ni<0||ni>=departmentList.length)return;[departmentList[idx],departmentList[ni]]=[departmentList[ni],departmentList[idx]];for(let i=0;i<departmentList.length;i++){await updateDoc(doc(db,"departments",departmentList[i].id),{sortOrder:i+1})}await loadDepartments()} window.moveDept=moveDept;

function renderMailTypeMaintenance(){
const area=$("mailTypeListArea");
if(!area)return;
const list=mailTypeList.length?mailTypeList:DEFAULT_MAIL_TYPES.map((name,index)=>({name,sortOrder:index+1,fallback:true}));
area.innerHTML=list.map(type=>`<div class="maintenance-item"><div><strong>${esc(type.name)}</strong><br><span>排序：${esc(type.sortOrder)}</span></div><div class="maintenance-actions">${type.fallback?"<span class='badge badge-yellow'>預設備援</span>":`<button class="btn btn-gray" onclick="renameMailType('${type.id}')">改名</button><button class="btn btn-gray" onclick="moveMailType('${type.id}',-1)">上移</button><button class="btn btn-gray" onclick="moveMailType('${type.id}',1)">下移</button><button class="btn btn-red" onclick="deleteMailType('${type.id}')">刪除</button>`}</div></div>`).join("");
}
function renderMailTypeMaintenanceError(error){
const area=$("mailTypeListArea");
if(!area)return;
area.innerHTML=`<div class="error-box"><b>郵件類型主檔讀取失敗</b><br>${esc(error?.message||error||"未知錯誤")}<br><span>目前仍使用程式內建類型。請確認 Firestore Rules 已允許 mailTypes 讀寫。</span></div>`;
}
async function addMailType(){if(blockUserAdminAction())return;const name=$("newMailType").value.trim(),sortOrder=parseInt($("newMailTypeOrder").value||mailTypeList.length+1);if(!name){alert("請輸入郵件類型名稱");return}if(currentMailTypes().some(type=>type.toLowerCase()===name.toLowerCase())){alert("此郵件類型已存在");return}const ref=await addDoc(collection(db,"mailTypes"),{name,sortOrder});await writeAuditLog({action:"create",category:"mailType",targetId:ref.id,targetLabel:name,after:{name,sortOrder}});$("newMailType").value="";$("newMailTypeOrder").value="";await loadMailTypes()} window.addMailType=addMailType;
async function renameMailType(id){if(blockUserAdminAction())return;const type=mailTypeList.find(item=>item.id===id);if(!type)return;const name=prompt("請輸入新的郵件類型名稱",type.name)?.trim();if(!name||name===type.name)return;if(mailTypeList.some(item=>item.id!==id&&item.name.toLowerCase()===name.toLowerCase())){alert("此郵件類型已存在");return}await updateDoc(doc(db,"mailTypes",id),{name});await writeAuditLog({action:"update",category:"mailType",targetId:id,targetLabel:name,before:type,after:{...type,name}});await loadMailTypes()} window.renameMailType=renameMailType;
async function deleteMailType(id){if(blockUserAdminAction())return;const type=mailTypeList.find(item=>item.id===id);if(!type)return;const usedCount=mailRecords.filter(record=>record.mailType===type.name).length;if(!confirm(usedCount?`已有 ${usedCount} 筆歷史郵件使用「${type.name}」。刪除後歷史資料仍會保留，但新登錄無法再選擇。確定刪除？`:`確定刪除郵件類型「${type.name}」？`))return;await deleteDoc(doc(db,"mailTypes",id));await writeAuditLog({action:"delete",category:"mailType",targetId:id,targetLabel:type.name,before:type});await loadMailTypes()} window.deleteMailType=deleteMailType;
async function moveMailType(id,dir){if(blockUserAdminAction())return;const idx=mailTypeList.findIndex(type=>type.id===id),nextIndex=idx+dir;if(idx<0||nextIndex<0||nextIndex>=mailTypeList.length)return;[mailTypeList[idx],mailTypeList[nextIndex]]=[mailTypeList[nextIndex],mailTypeList[idx]];for(let i=0;i<mailTypeList.length;i++)await updateDoc(doc(db,"mailTypes",mailTypeList[i].id),{sortOrder:i+1});await loadMailTypes()} window.moveMailType=moveMailType;

function renderUserList(){const area=$("userListArea");if(!area)return;area.innerHTML=userList.map(u=>`<div class="maintenance-item"><div><strong>${esc(u.email)}</strong><div style="margin-top:8px;display:flex;gap:12px;align-items:center;flex-wrap:wrap;"><span>角色：</span><select onchange="changeRole('${u.id}',this.value)"><option value="admin" ${u.role==="admin"?"selected":""}>Admin</option><option value="user" ${u.role==="user"?"selected":""}>User</option></select>${u.enabled?'<span class="badge badge-green">啟用</span>':'<span class="badge badge-red">停用</span>'}</div></div><div class="maintenance-actions"><button class="btn btn-gray" onclick="toggleUser('${u.id}',${!!u.enabled})">${u.enabled?'停用':'啟用'}</button><button class="btn btn-red" onclick="deleteUser('${u.id}')">刪除</button></div></div>`).join("")}
async function addWhitelistUser(){if(blockUserAdminAction())return;const email=$("newUserEmail").value.trim();if(!email){alert("請輸入 Email");return}const ref=await addDoc(collection(db,"users"),{email,role:"user",enabled:true});await writeAuditLog({action:"permission",category:"user",targetId:ref.id,targetLabel:email,after:{email,role:"user",enabled:true}});$("newUserEmail").value="";await loadUsers()} window.addWhitelistUser=addWhitelistUser;
async function changeRole(id,role){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);await updateDoc(doc(db,"users",id),{role});await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{...u,role}});await loadUsers()} window.changeRole=changeRole;
async function toggleUser(id,enabled){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);await updateDoc(doc(db,"users",id),{enabled:!enabled});await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{...u,enabled:!enabled}});await loadUsers()} window.toggleUser=toggleUser;
async function deleteUser(id){if(blockUserAdminAction())return;const u=userList.find(x=>x.id===id);if(u?.role==="admin"){alert("管理員不可刪除");return}if(!confirm("確定刪除使用者？"))return;await deleteDoc(doc(db,"users",id));await writeAuditLog({action:"permission",category:"user",targetId:id,targetLabel:u?.email,before:u,after:{deleted:true}});await loadUsers()} window.deleteUser=deleteUser;

async function loadAuditLogs(){if(!canAdmin())return;const snap=await getDocs(collection(db,"mailAuditLogs"));auditLogs=[];snap.forEach(s=>auditLogs.push({id:s.id,...s.data()}));auditLogs.sort((a,b)=>getTime(b.createdAt)-getTime(a.createdAt));renderAuditLogs()} window.loadAuditLogs=loadAuditLogs;
function renderAuditLogs(){const kw=($("auditSearch")?.value||"").toLowerCase(),act=$("auditActionFilter")?.value||"";const rows=auditLogs.filter(l=>(!act||l.action===act)&&(!kw||[l.actorName,l.actorEmail,l.targetLabel,JSON.stringify(l.after||{}),JSON.stringify(l.before||{})].join(" ").toLowerCase().includes(kw)));$("auditCount").textContent=`(${rows.length}筆)`;const total=Math.ceil(rows.length/auditPageSize)||1;if(auditCurrentPage>total)auditCurrentPage=1;const page=rows.slice((auditCurrentPage-1)*auditPageSize,auditCurrentPage*auditPageSize);$("auditLogTable").innerHTML=page.length?page.map(l=>`<tr><td>${esc(formatDate(l.createdAt))}</td><td>${esc(l.actorName||"-")}<div style="font-size:11px;color:#94a3b8">${esc(l.actorEmail||"")}</div></td><td>${esc(l.actorRole||"-")}</td><td><span class="badge badge-blue">${esc(actionLabel(l.action))}</span></td><td>${esc(categoryLabel(l.category))}</td><td>${esc(l.targetLabel||l.targetId||"-")}</td><td class="audit-detail">${esc(auditSummary(l))}</td></tr>`).join(""):`<tr><td colspan="7">目前沒有操作紀錄</td></tr>`;renderSimplePagination("auditPagination",total,auditCurrentPage,p=>{auditCurrentPage=p;renderAuditLogs()})}
function actionLabel(a){return {create:"新增",update:"修改",delete:"刪除",print:"列印",permission:"權限異動",login:"登入"}[a]||a||"-"}function categoryLabel(c){return {mailRecord:"郵件資料",outgoingMailBatch:"大宗寄件",department:"部門",mailType:"郵件類型",user:"使用者權限",signSheet:"簽收單"}[c]||c||"-"}function auditSummary(l){const o=l.after||l.before||{};return Object.entries(o).filter(([k])=>!["createdTime","printedAt","items"].includes(k)).map(([k,v])=>`${k}:${v}`).join("；")||"-"}
function changeAuditPageSize(){auditPageSize=parseInt($("auditPageSize").value);auditCurrentPage=1;renderAuditLogs()} window.changeAuditPageSize=changeAuditPageSize;function resetAuditFilter(){$("auditSearch").value="";$("auditActionFilter").value="";auditCurrentPage=1;renderAuditLogs()} window.resetAuditFilter=resetAuditFilter;
async function loadLoginLogs(){if(!canAdmin())return;const snap=await getDocs(collection(db,"mailLoginLogs"));loginLogs=[];snap.forEach(s=>loginLogs.push({id:s.id,...s.data()}));loginLogs.sort((a,b)=>getTime(b.loginTime)-getTime(a.loginTime));renderLoginLogs()} window.loadLoginLogs=loadLoginLogs;
function renderLoginLogs(){const total=Math.ceil(loginLogs.length/loginPageSize)||1;if(loginCurrentPage>total)loginCurrentPage=1;const page=loginLogs.slice((loginCurrentPage-1)*loginPageSize,loginCurrentPage*loginPageSize);$("loginCount").textContent=`(${loginLogs.length}筆)`;$("loginLogTable").innerHTML=page.length?page.map(l=>`<tr><td>${esc(formatDate(l.loginTime))}</td><td>${esc(l.name||"-")}</td><td>${esc(l.email||"-")}</td><td>${esc(l.role||"-")}</td></tr>`).join(""):`<tr><td colspan="4">目前沒有登入紀錄</td></tr>`;renderSimplePagination("loginPagination",total,loginCurrentPage,p=>{loginCurrentPage=p;renderLoginLogs()})}
function changeLoginPageSize(){loginPageSize=parseInt($("loginPageSize").value);loginCurrentPage=1;renderLoginLogs()} window.changeLoginPageSize=changeLoginPageSize;
function renderSimplePagination(id,total,current,cb){const area=$(id);if(!area)return;area.innerHTML="";if(total<=1)return;for(let i=1;i<=total;i++){const b=document.createElement("button");b.className="btn";b.textContent=i;b.style.background=i===current?"#2563eb":"#e2e8f0";b.style.color=i===current?"white":"#0f172a";b.onclick=()=>cb(i);area.appendChild(b)}}

["searchInput","typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].forEach(id=>document.addEventListener("input",e=>{if(e.target?.id===id){currentPage=1;renderMailTable()}}));document.addEventListener("change",e=>{if(["directionFilter","typeFilter","deptFilter","printedFilter","dateStart","dateEnd"].includes(e.target?.id)){currentPage=1;renderMailTable()}if(["auditSearch","auditActionFilter"].includes(e.target?.id)){auditCurrentPage=1;renderAuditLogs()}});
async function googleLogin(){try{await signInWithPopup(auth,provider)}catch(e){alert(e.message)}} window.googleLogin=googleLogin;
async function logout(){sessionStorage.removeItem("mailLoginLogged");localStorage.removeItem("userRole");localStorage.removeItem("userEmail");localStorage.removeItem("userName");await signOut(auth)} window.logout=logout;

onAuthStateChanged(auth,async(user)=>{if(!user){$("loginPage").style.display="flex";$("systemArea").style.display="none";return}const snap=await getDocs(collection(db,"users"));let allow=false,found=null;snap.forEach(s=>{const d=s.data();if(d.email===user.email&&d.enabled===true){allow=true;found=d}});if(!allow){alert("此帳號未開通");await signOut(auth);return}currentRole=found.role||"user";currentUser=user.displayName||user.email;currentUserEmail=user.email;localStorage.setItem("userRole",currentRole);localStorage.setItem("userEmail",user.email);localStorage.setItem("userName",currentUser);if(!sessionStorage.getItem("mailLoginLogged")){await addDoc(collection(db,"mailLoginLogs"),{name:currentUser,email:user.email,role:currentRole,loginTime:new Date()});sessionStorage.setItem("mailLoginLogged","true")}$("sidebarUserName").textContent=currentUser;$("sidebarUserEmail").textContent=user.email;$("loginPage").style.display="none";try{await Promise.all([loadDepartments(),loadMailTypes()]);await Promise.all([loadUsers(),loadMailRecords(),loadOutgoingBatches(),loadLoginLogs()]);}catch(error){console.error("系統初始化部分資料載入失敗",error);alert("系統資料載入失敗：" + (error?.message || error));}applyRoleAccess();restoreLastPage();$("systemArea").style.display="block";requestAnimationFrame(()=>$("systemArea").style.opacity="1");resetMailForm();prepareOutgoingPage();if(window.lucide)lucide.createIcons();});
})();
